package com.infosys.aetnams.queries;

public interface PortalQueries {
	
	public String GET_ALL_EMPLOYEES = "SELECT * FROM EMPLOYEE_MASTER";
	public String GET_BACKLOG_SDG1 = "SELECT * FROM  BACKLOG_MASTER WHERE ADA_SDG = 'SDG 1'";
	public String GET_BACKLOG_SDG2 = "SELECT * FROM  BACKLOG_MASTER WHERE ADA_SDG = 'SDG 2'";
	public String GET_BACKLOG_SDG3 = "SELECT * FROM  BACKLOG_MASTER WHERE ADA_SDG = 'SDG 3'";
	public String GET_BACKLOG_SDG4 = "SELECT * FROM  BACKLOG_MASTER WHERE ADA_SDG = 'SDG 4'";
	public String GET_BACKLOG_SDG5 = "SELECT * FROM  BACKLOG_MASTER WHERE ADA_SDG = 'SDG 5'";


	public String APPLICATION_DETAILS1 = "SELECT * FROM APPLICATION_MASTER WHERE SDG = '1'";
	public String APPLICATION_DETAILS2 = "SELECT * FROM APPLICATION_MASTER WHERE SDG = '2'";
	public String APPLICATION_DETAILS3 = "SELECT * FROM APPLICATION_MASTER WHERE SDG = '3'";
	public String APPLICATION_DETAILS4 = "SELECT * FROM APPLICATION_MASTER WHERE SDG = '4'";
	public String APPLICATION_DETAILS5 = "SELECT * FROM APPLICATION_MASTER WHERE SDG = '5'";
	
	
	public String SR_DETAILS1 = "SELECT * FROM SERVICE_REQUEST_MASTER WHERE SDG ='1'";
	public String SR_DETAILS2 = "SELECT * FROM SERVICE_REQUEST_MASTER WHERE SDG ='2'";
	public String SR_DETAILS3 = "SELECT * FROM SERVICE_REQUEST_MASTER WHERE SDG ='3'";
	public String SR_DETAILS4 = "SELECT * FROM SERVICE_REQUEST_MASTER WHERE SDG ='4'";
	public String SR_DETAILS5 = "SELECT * FROM SERVICE_REQUEST_MASTER WHERE SDG ='5'";
	
	
	public String SRE_TOTAL1 = "SELECT SUM(SRE_Count) as TOTALSRE FROM SERVICE_REQUEST_MASTER WHERE SDG ='1' AND Implementation_Date Between ? AND ?";
	public String SRE_TOTAL2 = "SELECT SUM(SRE_Count) as TOTALSRE FROM SERVICE_REQUEST_MASTER WHERE SDG ='2' AND Implementation_Date Between ? AND ?";
	public String SRE_TOTAL3 = "SELECT SUM(SRE_Count) as TOTALSRE FROM SERVICE_REQUEST_MASTER WHERE SDG ='3' AND Implementation_Date Between ? AND ?";
	public String SRE_TOTAL4 = "SELECT SUM(SRE_Count) as TOTALSRE FROM SERVICE_REQUEST_MASTER WHERE SDG ='4' AND Implementation_Date Between ? AND ?";
	public String SRE_TOTAL5 = "SELECT SUM(SRE_Count) as TOTALSRE FROM SERVICE_REQUEST_MASTER WHERE SDG ='5' AND Implementation_Date Between ? AND ?";
	
	
}
